#!/bin/sh

# You may find this shell script helpful.

java -mx2000m -cp bin \
  cs224n.assignments.LanguageModelTester \
  -model cs224n.langmodel.ZipfChimeraInterpolatedTriGramModel \
  -data      /Users/yfriedman/cs224n/pa1/data \
  -train     europarl-train.sent.txt \
  -test      europarl-test.sent.txt \
  -generate  true \
  -serialize true \
  $@
