#!/bin/sh

# You may find this shell script helpful.

java -mx3000m -cp classes \
  cs224n.assignments.LanguageModelTester \
  -model cs224n.langmodel.ZipfChimeraInterpolatedTriGramModel \
  -data      /usr/local/google/cs224n/crawled/crawled/parsed_raw \
  -train     europarl-train.sent.txt \
  -test      europarl-test.sent.txt \
  -generate  true \
  -serialize true \
  $@
