#!/bin/sh

# You may find this shell script helpful.

java -mx3000m -cp classes \
  cs224n.assignments.LanguageModelTester \
  -model cs224n.langmodel.ZipfChimeraInterpolatedTriGramModel \
  -data      ../data/parsed \
  -train     europarl-train.sent.txt \
  -generate  true \
  -serialize true \
  $@
