#!/bin/sh

# You may find this shell script helpful.

java -mx200m -cp classes \
  cs224n.assignments.LanguageModelTester \
  -model cs224n.langmodel.EmpiricalUnigramLanguageModel \
  -data      /afs/ir/class/cs224n/pa1/data \
  -train     europarl-train.sent.txt \
  -test      europarl-test.sent.txt \
  -showguesses       false \
  -jumble       true \
  -baselines true \
  -generate  true \
  $@
